version: '3'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    container_name: app
    build:
      context: node
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node app.js
    volumes:
      - ./node:/app
      - /node/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge